# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 21:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Enter in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
