# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 23:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20160426_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Enter in the format: '+0123456789'. Up to 15 digits allowed.")]),
        ),
    ]
