# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20160427_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default='London', max_length=30),
            preserve_default=False,
        ),
    ]
